- name: (sysconf) create oracle group
  group:
    name: "{{ oracle_group }}"
    system: true

- name: (sysconf) create oracle user
  user:
    name: oracle
    group: "{{ oracle_group }}"
    groups: ["trusted"]
    system: true

# depends on "ypbind" by default
- name: (sysconf) fix oracle init script
  lineinfile:
    dest: "/etc/init.d/oracle-xe"
    regexp: "^# Required-Start:"
    line:    "# Required-Start: $local_fs $remote_fs $network"

# hard-coded vars, owned by orarun (may be overwriten on (not highly probable) next update)
- name: (sysconf) replace /etc/profile.d/oracle.sh
  template:
    src:   "oracle.sh.j2"
    dest:  "/etc/profile.d/oracle.sh"
    owner: root
    group: wheel
    mode:  0644

# orarun configures it, but lets raise limits a bit
- name: (sysconf) tune limits.conf
  pam_limits:
    domain: oracle
    limit_item: "{{ item[0].key }}"
    limit_type: "{{ item[1] }}"
    value:      "{{ item[0].value }}"
  with_nested:
    - "{{ oracle_pam_limits | dict2list }}"
    - ['soft', 'hard']

- name: (sysconf) set kernel parameters
  sysctl:
    name:   "{{ item.key }}"
    value:  "{{ item.value }}"
    state:  present
    reload: true
    ignoreerrors: true
  with_dict: "{{ oracle_kernel_params }}"

# splash=0 is a weak way to get main kernel, but insertbefore is not compatible with backrefs
- name: (sysconf) mod grub params
  lineinfile:
    dest:   '/boot/grub/menu.lst'
    regexp: '^    kernel (.* splash=0 .*)(?:{{ item.key }}=\S+)(.*)$'
    line:   '    kernel \1{{ item.key }}={{ item.value }}\2'
    backrefs: true
  with_dict: "{{ oracle_grub_params }}"

- name: (sysconf) add grub params
  lineinfile:
    dest:   '/boot/grub/menu.lst'
    regexp: '^    kernel (.* splash=0 ?)(?!.*{{ item.key }}=)(.*)$'
    line:   '    kernel \1\2 {{ item.key }}={{ item.value }}'
    backrefs: true
  with_dict: "{{ oracle_grub_params }}"

- name: (sysconf) add users to dba group
  user:
    name:   "{{ item }}"
    groups: "{{ oracle_dba_group }}"
    append: true
  with_items: "{{ oracle_dba_users }}"

- name: (sysconf) set ownership for oracle base dir
  file:
    path:  "{{ oracle_base }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode:  "u+rwx,og+rx"

- name: (sysconf) make sure apps dir exists
  file:
    path: "/apps/oracle/"
    state: directory

- name: (sysconf) add compatiblity symlink from apps
  file:
    path: "/apps/oracle/base"
    src:  "/u01/app/oracle"
    state: link
